[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt", "npm install --prefix frontend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[phases.start]
cmds = ["hypercorn backend.main:app --bind \"[::]:$PORT\""]
