[phases.setup]
nixPkgs = ["python309", "gcc"]

[phases.build]
cmds = [
  "cd backend && python3 -m pip install --upgrade pip",
  "cd backend && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
