[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.build]
cmds = ["python3 -m ensurepip", "pip install --upgrade pip", "pip install -r backend/requirements.txt"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
