"""Actualización del modelo de base de datos 5

Revision ID: 02335a8777dc
Revises: b759fd1455a3
Create Date: 2025-03-26 09:53:59.941713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02335a8777dc'
down_revision: Union[str, None] = 'b759fd1455a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arrangements', 'arr_discount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('orders', 'order_pay_type')
    op.drop_column('orders', 'preferred_payment_method')
    op.drop_column('orders', 'order_total')
    op.drop_column('orders', 'subtotal')
    op.add_column('payments', sa.Column('pay_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'pay_amount')
    op.add_column('orders', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('preferred_payment_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('order_pay_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('arrangements', 'arr_discount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
