"""Actualización del modelo de base de datos 12

Revision ID: 29d04e3c617f
Revises: c4c744ce4680
Create Date: 2025-05-13 11:15:30.086333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d04e3c617f'
down_revision: Union[str, None] = 'c4c744ce4680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_comments')
    # ### end Alembic commands ###
