"""Actualización del modelo de base de datos 6

Revision ID: 2c4a053c949a
Revises: 02335a8777dc
Create Date: 2025-03-31 09:35:36.988163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4a053c949a'
down_revision: Union[str, None] = '02335a8777dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_email', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('guest_address', sa.String(), nullable=True))
    op.alter_column('orders', 'order_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'guest_address')
    op.drop_column('orders', 'guest_phone')
    op.drop_column('orders', 'guest_email')
    op.drop_column('orders', 'guest_name')
    # ### end Alembic commands ###
