"""Actualización del modelo de base de datos 9

Revision ID: 3510856c39ca
Revises: c6511853a08a
Create Date: 2025-05-01 16:29:07.850644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3510856c39ca'
down_revision: Union[str, None] = 'c6511853a08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_visits_id', table_name='site_visits')
    op.drop_table('site_visits')
    op.drop_index('ix_product_views_id', table_name='product_views')
    op.drop_table('product_views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['arrangements.id'], name='product_views_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_views_pkey')
    )
    op.create_index('ix_product_views_id', 'product_views', ['id'], unique=False)
    op.create_table('site_visits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='site_visits_pkey')
    )
    op.create_index('ix_site_visits_id', 'site_visits', ['id'], unique=False)
    # ### end Alembic commands ###
