"""Actualización del modelo de base de datos 7

Revision ID: 6f3341855639
Revises: 2c4a053c949a
Create Date: 2025-04-30 23:22:35.446741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3341855639'
down_revision: Union[str, None] = '2c4a053c949a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_account_state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_account_state')
    # ### end Alembic commands ###
