"""Actualización del modelo de base de datos 4

Revision ID: b759fd1455a3
Revises: 52b63c69b821
Create Date: 2025-03-21 12:15:38.842955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b759fd1455a3'
down_revision: Union[str, None] = '52b63c69b821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangements', sa.Column('arr_discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arrangements', 'arr_discount')
    # ### end Alembic commands ###
