"""Actualización del modelo de base de datos

Revision ID: cdc49f898d61
Revises: 
Create Date: 2025-03-13 14:17:21.679461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdc49f898d61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.add_column('arrangements', sa.Column('arr_id_cat', sa.Integer(), nullable=False))
    op.add_column('arrangements', sa.Column('arr_stock', sa.Integer(), nullable=True))
    op.alter_column('arrangements', 'arr_availability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'arrangements', 'categories', ['arr_id_cat'], ['id'])
    op.alter_column('comments', 'comment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('payments', sa.Column('pay_transaction_id', sa.String(), nullable=True))
    op.alter_column('payments', 'pay_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'payments', ['pay_transaction_id'])
    op.add_column('users', sa.Column('user_direction', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_number', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_url_photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_google_id', sa.String(), nullable=True))
    op.alter_column('users', 'user_register_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['user_google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'user_register_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'user_google_id')
    op.drop_column('users', 'user_url_photo')
    op.drop_column('users', 'user_number')
    op.drop_column('users', 'user_direction')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'pay_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('payments', 'pay_transaction_id')
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'comment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'arrangements', type_='foreignkey')
    op.alter_column('arrangements', 'arr_availability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('arrangements', 'arr_stock')
    op.drop_column('arrangements', 'arr_id_cat')
    op.create_table('games',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('juego', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('runN', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rejugando', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('DatosAdicionales', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Calificacion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_finalizado', sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
