"""Base de datos cambio categorias

Revision ID: d301b0809c75
Revises: a7373d5aaf93
Create Date: 2025-05-19 21:03:41.725271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd301b0809c75'
down_revision: Union[str, None] = 'a7373d5aaf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrangement_category',
    sa.Column('arrangement_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrangement_id'], ['arrangements.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('arrangement_id', 'category_id')
    )
    op.drop_constraint('arrangements_arr_id_cat_fkey', 'arrangements', type_='foreignkey')
    op.drop_column('arrangements', 'arr_id_cat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrangements', sa.Column('arr_id_cat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('arrangements_arr_id_cat_fkey', 'arrangements', 'categories', ['arr_id_cat'], ['id'])
    op.drop_table('arrangement_category')
    # ### end Alembic commands ###
