"""Actualización del modelo de base de datos 2

Revision ID: fdbd9f65315f
Revises: cdc49f898d61
Create Date: 2025-03-19 14:48:06.427610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbd9f65315f'
down_revision: Union[str, None] = 'cdc49f898d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('preferred_payment_method', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('orders_details', sa.Column('discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_details', 'discount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'preferred_payment_method')
    # ### end Alembic commands ###
